/* Giga Knowledge Hub V6 Cloud Layer */
(()=>{
const C=window.GKH_SUPABASE; let sb=null,user=null,syncing=false;
const $=id=>document.getElementById(id); const esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cloudReady(){return !!(C&&window.supabase)}
function setCloudStatus(text,state='local'){let e=$('cloudStatus');if(!e)return;e.textContent=text;e.dataset.state=state}
function authButton(){let b=$('authBtn');if(!b)return;b.textContent=user?'☁ '+(user.email||'Account'):'☁ Sign in';b.title=user?'Cloud account & sync':'Sign in for cloud sync'}
async function initCloud(){if(!cloudReady()){setCloudStatus('Local only');return} sb=window.supabase.createClient(C.url,C.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});let {data}=await sb.auth.getSession();user=data.session?.user||null;authButton();setCloudStatus(user?'Cloud connected':'Local only',user?'online':'local');sb.auth.onAuthStateChange(async(ev,session)=>{user=session?.user||null;authButton();setCloudStatus(user?'Cloud connected':'Local only',user?'online':'local');if(user&&['SIGNED_IN','INITIAL_SESSION'].includes(ev)) await cloudBootstrap()});if(user)await cloudBootstrap()}
function openAuth(){if(user)return accountModal();modal('Cloud Account',`<div class="cloud-intro"><b>V6 Cloud Sync</b><p class="muted">Sign in to sync your workspace across devices and use private file storage.</p></div><div class="form-grid"><div class="field full"><label>Email</label><input id="authEmail" type="email" autocomplete="email"></div><div class="field full"><label>Password</label><input id="authPassword" type="password" autocomplete="current-password"></div></div><div class="actions"><button class="btn primary" onclick="cloudSignIn()">Sign in</button><button class="btn" onclick="cloudSignUp()">Create account</button><button class="btn" onclick="cloudResetPassword()">Reset password</button></div>`)}
function accountModal(){modal('Cloud Account',`<div class="notice"><b>${esc2(user.email||'Signed in')}</b><div class="muted">Supabase · RLS protected · V6</div></div><div class="actions"><button class="btn primary" onclick="cloudSyncNow()">↻ Sync now</button><button class="btn" onclick="cloudUploadLocal()">↑ Upload local workspace</button><button class="btn" onclick="cloudPull()">↓ Pull cloud workspace</button><button class="btn danger" onclick="cloudSignOut()">Sign out</button></div><p class="muted" style="font-size:10px">First sync merges seed/local items with your cloud workspace. Private files are stored in a user-isolated bucket.</p>`)}
async function cloudSignIn(){let email=$('authEmail').value.trim(),password=$('authPassword').value;let {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);closeModal();toast('Cloud sign-in successful')}
async function cloudSignUp(){let email=$('authEmail').value.trim(),password=$('authPassword').value;if(password.length<6)return toast('Use at least 6 characters');let {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)return toast(error.message);closeModal();toast(data.session?'Account created':'Check your email to confirm the account')}
async function cloudResetPassword(){let email=$('authEmail').value.trim();if(!email)return toast('Enter your email first');let {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Password reset email requested')}
async function cloudSignOut(){await sb.auth.signOut();closeModal();toast('Signed out · local data remains on this device')}
async function cloudBootstrap(){if(syncing||!user)return;syncing=true;setCloudStatus('Syncing…','sync');try{let {data:objs,error}=await sb.from('objects').select('*');if(error)throw error;if(!objs?.length){await cloudUploadLocal(false)}else{await cloudPull(false)}setCloudStatus('Cloud synced','online')}catch(e){console.error(e);setCloudStatus('Sync error','error');toast('Cloud sync: '+e.message)}finally{syncing=false}}
const statusToDb=s=>s==='To Do'?'todo':s==='In Progress'?'in_progress':'done', statusFromDb=s=>s==='todo'?'To Do':s==='in_progress'?'In Progress':'Done';
async function cloudUploadLocal(notify=true){if(!user)return openAuth();setCloudStatus('Uploading…','sync');let uid=user.id;try{let objRows=(DB.objects||[]).map(o=>({user_id:uid,client_id:o.id,scope:o.scope,type:o.type||'item',title:o.title,summary:o.summary||null,status:o.status||null,priority:o.priority||null,tags:o.tags||[],data:{...o},favorite:DB.favorites.includes(o.id),archived:!!o.archived}));if(objRows.length){let {error}=await sb.from('objects').upsert(objRows,{onConflict:'user_id,client_id'});if(error)throw error}let {data:cloudObjs,error:oe}=await sb.from('objects').select('id,client_id');if(oe)throw oe;let map=Object.fromEntries((cloudObjs||[]).map(x=>[x.client_id,x.id]));await replaceOwned('edges',(DB.edges||[]).filter(e=>map[e.from]&&map[e.to]).map(e=>({user_id:uid,from_object:map[e.from],to_object:map[e.to],relation:e.type||'related_to'})));await replaceOwned('notes',(DB.notes||[]).map(n=>({user_id:uid,object_id:map[n.objectId]||null,body:n.text||n.body||''})));await replaceOwned('tasks',(DB.tasks||[]).map(t=>({user_id:uid,object_id:map[t.objectId]||null,title:t.title,status:statusToDb(t.status),due_date:t.due||null,priority:t.priority||null,data:{client_id:t.id}})));await replaceOwned('events',(DB.events||[]).map(e=>({user_id:uid,object_id:map[e.objectId]||null,title:e.title,starts_at:e.date?e.date+'T12:00:00+04:00':(e.starts_at||new Date().toISOString()),data:{client_id:e.id}})));let src=(DB.sources||[]).map(s=>({user_id:uid,name:s.name,url:s.url||null,scope:s.scope||null,reliability_tier:s.tier||s.reliability_tier||null,enabled:s.enabled!==false,data:{client_id:s.id}}));await replaceOwned('sources',src);await sb.from('sync_state').upsert({user_id:uid,last_synced_at:new Date().toISOString(),client_version:C.version,data:{origin:location.href}},{onConflict:'user_id'});setCloudStatus('Cloud synced','online');if(notify)toast('Workspace uploaded to cloud')}catch(e){setCloudStatus('Sync error','error');toast(e.message)}}
async function replaceOwned(table,rows){let {error:d}=await sb.from(table).delete().eq('user_id',user.id);if(d)throw d;if(rows.length){let {error}=await sb.from(table).insert(rows);if(error)throw error}}
async function cloudPull(notify=true){if(!user)return openAuth();setCloudStatus('Downloading…','sync');try{let [oo,ee,nn,tt,vv,ss,ff]=await Promise.all([sb.from('objects').select('*'),sb.from('edges').select('*'),sb.from('notes').select('*'),sb.from('tasks').select('*'),sb.from('events').select('*'),sb.from('sources').select('*'),sb.from('files').select('*')]);for(let r of [oo,ee,nn,tt,vv,ss,ff])if(r.error)throw r.error;let byUuid=Object.fromEntries(oo.data.map(o=>[o.id,o.client_id||o.id]));DB.objects=oo.data.map(o=>({...o.data,id:o.client_id||o.id,scope:o.scope,type:o.type,title:o.title,summary:o.summary||'',status:o.status,priority:o.priority,tags:o.tags||[],archived:o.archived}));DB.favorites=oo.data.filter(o=>o.favorite).map(o=>o.client_id||o.id);DB.edges=ee.data.map(e=>({from:byUuid[e.from_object],to:byUuid[e.to_object],type:e.relation})).filter(e=>e.from&&e.to);DB.notes=nn.data.map(n=>({id:n.id,objectId:byUuid[n.object_id]||null,text:n.body,createdAt:n.created_at}));DB.tasks=tt.data.map(t=>({id:t.data?.client_id||t.id,objectId:byUuid[t.object_id]||null,title:t.title,status:statusFromDb(t.status),due:t.due_date,priority:t.priority}));DB.events=vv.data.map(e=>({id:e.data?.client_id||e.id,objectId:byUuid[e.object_id]||null,title:e.title,date:(e.starts_at||'').slice(0,10)}));DB.sources=ss.data.map(s=>({id:s.data?.client_id||s.id,name:s.name,url:s.url,scope:s.scope,tier:s.reliability_tier,enabled:s.enabled}));DB.cloudFiles=ff.data;save();renderHome();setCloudStatus('Cloud synced','online');if(notify)toast('Cloud workspace loaded')}catch(e){setCloudStatus('Sync error','error');toast(e.message)}}
async function cloudSyncNow(){closeModal();await cloudUploadLocal(false);await cloudPull(false);toast('Cloud sync complete')}
async function uploadPrivateFile(file,objectClientId=null,tags=[]){if(!user)return openAuth();let safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${user.id}/${crypto.randomUUID()}/${safe}`;let {error}=await sb.storage.from(C.bucket).upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error)return toast(error.message);let object_id=null;if(objectClientId){let {data}=await sb.from('objects').select('id').eq('client_id',objectClientId).maybeSingle();object_id=data?.id||null}let {error:dbErr}=await sb.from('files').insert({user_id:user.id,object_id,bucket:C.bucket,path,name:file.name,mime_type:file.type||null,size_bytes:file.size,tags});if(dbErr)return toast(dbErr.message);toast('Private file uploaded');await cloudPull(false);renderFiles()}
async function openPrivateFile(id){let f=(DB.cloudFiles||[]).find(x=>x.id===id);if(!f)return;let {data,error}=await sb.storage.from(f.bucket).createSignedUrl(f.path,60);if(error)return toast(error.message);window.open(data.signedUrl,'_blank','noopener')}
async function deletePrivateFile(id){let f=(DB.cloudFiles||[]).find(x=>x.id===id);if(!f)return;let {error}=await sb.storage.from(f.bucket).remove([f.path]);if(error)return toast(error.message);await sb.from('files').delete().eq('id',id);await cloudPull(false);renderFiles();toast('File deleted')}
window.openAuth=openAuth;window.cloudSignIn=cloudSignIn;window.cloudSignUp=cloudSignUp;window.cloudResetPassword=cloudResetPassword;window.cloudSignOut=cloudSignOut;window.cloudSyncNow=cloudSyncNow;window.cloudUploadLocal=cloudUploadLocal;window.cloudPull=cloudPull;window.uploadPrivateFile=uploadPrivateFile;window.openPrivateFile=openPrivateFile;window.deletePrivateFile=deletePrivateFile;window.GKHCloud={init:initCloud,get client(){return sb},get user(){return user}};
window.addEventListener('DOMContentLoaded',()=>setTimeout(initCloud,80));
})();
