import "jsr:@supabase/functions-js/edge-runtime.d.ts";
// V6.2 production ingestion: official FC Barcelona + APM Terminals sources.
// Scheduler authentication is configured in Supabase/Vault and intentionally not stored in this public repository.
const SOURCES=[{name:"FC Barcelona",scope:"football",tier:"Official",url:"https://www.fcbarcelona.com/en/football/first-team/news",kind:"barca"},{name:"APM Terminals",scope:"logistics",tier:"Official",url:"https://akamai.apmterminals.com/en/news/news-releases",kind:"apmt"}];
const clean=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&nbsp;/g," ").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const abs=(b:string,u:string)=>{try{return new URL(u,b).href}catch{return""}};async function sha1(s:string){const b=await crypto.subtle.digest("SHA-1",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("").slice(0,16)}
function relevant(src:any,href:string,title:string){if(src.kind==='barca')return /fcbarcelona\.com\/en\/(?:football\/first-team\/news|news)\//i.test(href)&&!/(tickets|shop|museum)/i.test(title);return /apmterminals\.com\/en\/(?:news\/news-releases|[^/]+\/(?:our-port|about)\/news)/i.test(href)}
function priority(src:any,t:string){if(src.kind==='barca')return 'High Priority';return /poti|georgia|black sea|middle corridor|apm terminals|terminal|port/i.test(t)?'High Priority':/container|shipping|logistics|maritime/i.test(t)?'Relevant':'More News'}
function barcaTitle(t:string){return t.replace(/^FC Barcelona club badge\s*/i,'').replace(/\s+First Team(?:\s+clock)?\s+Published date\s+.*$/i,'').trim()}
async function page(src:any){const r=await fetch(src.url,{redirect:'follow',headers:{"User-Agent":"Mozilla/5.0 (compatible; GigaKnowledgeHub/6.2)",Accept:"text/html,application/xhtml+xml"}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);const h=await r.text(),c:any[]=[],re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(h))&&c.length<1000){const href=abs(src.url,m[1]).split('#')[0],raw=clean(m[2]);if(raw.length<18||raw.length>240||!relevant(src,href,raw))continue;c.push({href,raw})}const d=[...new Map(c.map(x=>[x.href.split(/[?#]/)[0],x])).values()].slice(0,20),out:any[]=[];for(const x of d){const canonical=x.href.split(/[?#]/)[0],title=src.kind==='barca'?barcaTitle(x.raw):x.raw;out.push({external_id:await sha1(src.name+canonical),scope:src.scope,source_name:src.name,source_url:canonical,title,summary:null,published_at:null,priority:priority(src,title),verification:"Official / Confirmed",cluster_key:null,tags:src.kind==='barca'?['FC Barcelona']:['APM Terminals','Ports'],source_tier:src.tier,data:{adapter:"html-link-discovery-v4",source_page:src.url}})}return out}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return Response.json({error:"POST required"},{status:405});const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return Response.json({error:"Supabase environment unavailable"},{status:500});const all:any[]=[],health:any[]=[];for(const s of SOURCES){try{const g=await page(s);all.push(...g);health.push({source:s.name,ok:true,items:g.length})}catch(e){health.push({source:s.name,ok:false,items:0,error:String(e)})}}const u=[...new Map(all.map(x=>[x.source_url.toLowerCase(),x])).values()];if(u.length){const r=await fetch(`${url}/rest/v1/news_items?on_conflict=external_id`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(u)});if(!r.ok)return Response.json({error:"db",detail:await r.text(),health},{status:500})}return Response.json({ok:true,count:u.length,health})});